[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.8",
    "django-environ>=0.12.0",
    "django-extensions>=4.1",
    "ipython>=9.7.0",
    "psycopg2-binary>=2.9.11",
    "uuid6>=2025.0.1",
]

[dependency-groups]
dev = [
    "faker>=37.12.0",
    "model-bakery>=1.20.5",
    "pytest>=9.0.0",
    "pytest-django>=4.11.1",
]
