[pytest]
DJANGO_SETTINGS_MODULE = config.settings.dev
python_files = tests.py test_*.py *_tests.py *_test.py
python_classes = Test*
python_functions = test_*
addopts = -v --strict-markers --tb=short
testpaths = app/tests
