# Generated by Django 5.2.8 on 2025-11-24 01:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateStatus',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ステータスコード')),
                ('name', models.CharField(max_length=50, verbose_name='ステータス名')),
            ],
            options={
                'verbose_name': '更新ステータス',
                'verbose_name_plural': '更新ステータス',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='組織名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.organization', verbose_name='親組織')),
            ],
            options={
                'verbose_name': '組織',
                'verbose_name_plural': '組織',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新規作成'), ('update', '更新'), ('delete', '削除')], max_length=10, verbose_name='操作種別')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='組織名')),
                ('scheduled_date', models.DateField(verbose_name='適用予定日')),
                ('organization', models.ForeignKey(blank=True, help_text='新規作成の場合はNull', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.organization', verbose_name='対象組織')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_reservations', to='app.organization', verbose_name='親組織')),
                ('status', models.ForeignKey(default='pending', on_delete=django.db.models.deletion.PROTECT, to='app.updatestatus', verbose_name='ステータス')),
            ],
            options={
                'verbose_name': '組織予約更新',
                'verbose_name_plural': '組織予約更新',
                'ordering': ['scheduled_date', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['parent'], name='app_organiz_parent__9b9e31_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationreservation',
            index=models.Index(fields=['scheduled_date', 'status'], name='app_organiz_schedul_f16990_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationreservation',
            index=models.Index(fields=['organization'], name='app_organiz_organiz_0bb24f_idx'),
        ),
    ]
