# Generated by Django 5.2.8 on 2025-11-24 04:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0006_reservation_migrate_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200, verbose_name='氏名')),
                (
                    'email',
                    models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
                ),
            ],
            options={
                'verbose_name': '社員',
                'verbose_name_plural': '社員',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='app_reserva_schedul_d5c342_idx',
            old_name='app_reserva_schedul_9c8e7e_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='app_reserva_content_192650_idx',
            old_name='app_reserva_content_f3a2d1_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='app_reserva_depends_24032b_idx',
            old_name='app_reserva_depends_a1b2c3_idx',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='depends_on',
            field=models.ForeignKey(
                blank=True,
                help_text='未適用の予約を親として指定する場合に設定',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='dependents',
                to='app.reservation',
                verbose_name='依存予約（親として使用）',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='employees',
                to='app.department',
                verbose_name='所属組織',
            ),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='app_employe_departme_8f818c_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='app_employe_email_8dc4ec_idx'),
        ),
    ]
