# Generated by Django 5.2.8 on 2025-12-08 07:54

from django.db import migrations, models


def migrate_status_data(apps, schema_editor):
    """既存のstatus_idデータを新しいstatusフィールドに移行"""
    Reservation = apps.get_model('app', 'Reservation')
    db_alias = schema_editor.connection.alias
    # status_idの値（pending/applied/cancelledの文字列）を新しいstatusフィールドにコピー
    for reservation in Reservation.objects.using(db_alias).all():
        # UpdateStatusモデルのprimary keyは文字列（pending/applied/cancelled）なので、
        # 直接その値を新しいstatusフィールドに設定
        reservation.status_new = reservation.status_id
        reservation.save(update_fields=['status_new'])


def reverse_migrate_status_data(apps, schema_editor):
    """ロールバック用: statusデータをstatus_idに戻す"""
    Reservation = apps.get_model('app', 'Reservation')
    db_alias = schema_editor.connection.alias
    for reservation in Reservation.objects.using(db_alias).all():
        reservation.status_id = reservation.status_new
        reservation.save(update_fields=['status_id'])


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0009_alter_employee_email'),
    ]

    operations = [
        # 1. 新しいstatusフィールドを追加（null許可）
        migrations.AddField(
            model_name='reservation',
            name='status_new',
            field=models.CharField(
                choices=[
                    ('pending', '予約中'),
                    ('applied', '適用済み'),
                    ('cancelled', 'キャンセル済み'),
                ],
                default='pending',
                max_length=20,
                verbose_name='ステータス',
                null=True,
            ),
        ),
        # 2. データを移行
        migrations.RunPython(migrate_status_data, reverse_migrate_status_data),
        # 3. 古いstatusフィールド（ForeignKey）を削除
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        # 4. 新しいstatusフィールドの名前を変更
        migrations.RenameField(
            model_name='reservation',
            old_name='status_new',
            new_name='status',
        ),
        # 5. nullを不許可に変更
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', '予約中'),
                    ('applied', '適用済み'),
                    ('cancelled', 'キャンセル済み'),
                ],
                default='pending',
                max_length=20,
                verbose_name='ステータス',
            ),
        ),
        # 6. UpdateStatusモデルを削除
        migrations.DeleteModel(
            name='UpdateStatus',
        ),
    ]
