# Generated by Django 5.2.8 on 2025-12-08 08:42

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0010_remove_updatestatus_model'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedChange',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                (
                    'object_id',
                    models.UUIDField(
                        blank=True,
                        help_text='新規作成の場合はNull',
                        null=True,
                        verbose_name='対象オブジェクトID',
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('create', '新規作成'),
                            ('update', '更新'),
                            ('delete', '削除'),
                            ('merge', '統合'),
                        ],
                        max_length=10,
                        verbose_name='操作種別',
                    ),
                ),
                (
                    'data',
                    models.JSONField(
                        help_text='更新する内容をJSON形式で保存', verbose_name='更新データ'
                    ),
                ),
                ('scheduled_date', models.DateField(verbose_name='適用予定日')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', '予約中'),
                            ('applied', '適用済み'),
                            ('cancelled', 'キャンセル済み'),
                        ],
                        default='pending',
                        max_length=20,
                        verbose_name='ステータス',
                    ),
                ),
                (
                    'applied_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='適用日時'),
                ),
                (
                    'applied_object_id',
                    models.UUIDField(
                        blank=True,
                        help_text='新規作成時に生成されたオブジェクトのID',
                        null=True,
                        verbose_name='適用後オブジェクトID',
                    ),
                ),
            ],
            options={
                'verbose_name': '予約更新',
                'verbose_name_plural': '予約更新',
                'ordering': ['scheduled_date', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='depends_on',
        ),
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='app_departm_parent__6978d3_idx',
            old_name='app_organiz_parent__9b9e31_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='app_employe_departm_1ec737_idx',
            old_name='app_employe_departme_8f818c_idx',
        ),
        migrations.AddField(
            model_name='stagedchange',
            name='content_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
                verbose_name='対象モデル',
            ),
        ),
        migrations.AddField(
            model_name='stagedchange',
            name='depends_on',
            field=models.ForeignKey(
                blank=True,
                help_text='未適用の予約を親として指定する場合に設定',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='dependents',
                to='app.stagedchange',
                verbose_name='依存予約（親として使用）',
            ),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.AddIndex(
            model_name='stagedchange',
            index=models.Index(
                fields=['scheduled_date', 'status'], name='app_stagedc_schedul_757dd7_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='stagedchange',
            index=models.Index(
                fields=['content_type', 'object_id'], name='app_stagedc_content_2b4394_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='stagedchange',
            index=models.Index(fields=['depends_on'], name='app_stagedc_depends_e9f85d_idx'),
        ),
    ]
