# Generated by Django 5.2.8 on 2025-12-08 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0011_stagedchange_remove_reservation_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': '部門', 'verbose_name_plural': '部門'},
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=7, null=True, verbose_name='部門コード'),
        ),
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(max_length=7, null=True, verbose_name='社員コード'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='部門名'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='app.department',
                verbose_name='親部門',
            ),
        ),
    ]
