from app.views.article import (
    ArticleCreateView,
    ArticleDeleteView,
    ArticleDetailView,
    ArticleUpdateView,
    IndexView,
    LoginView,
    LogoutView,
)
from app.views.department import (
    DepartmentCreateView,
    DepartmentDeleteView,
    DepartmentListView,
    DepartmentMergeView,
    DepartmentUpdateView,
)
from app.views.employee import (
    EmployeeCreateView,
    EmployeeDeleteView,
    EmployeeListView,
    EmployeePreviewView,
    EmployeeReservationCreateView,
    EmployeeReservationDeleteView,
    EmployeeReservationListView,
    EmployeeReservationUpdateView,
    EmployeeUpdateView,
)
from app.views.reservation import (
    DepartmentPreviewView,
    DepartmentReservationCreateView,
    DepartmentReservationDeleteView,
    DepartmentReservationListView,
    DepartmentReservationUpdateView,
)

__all__ = [
    'ArticleCreateView',
    'ArticleDeleteView',
    'ArticleDetailView',
    'ArticleUpdateView',
    'DepartmentCreateView',
    'DepartmentDeleteView',
    'DepartmentListView',
    'DepartmentMergeView',
    'DepartmentPreviewView',
    'DepartmentReservationCreateView',
    'DepartmentReservationDeleteView',
    'DepartmentReservationListView',
    'DepartmentReservationUpdateView',
    'DepartmentUpdateView',
    'EmployeeCreateView',
    'EmployeeDeleteView',
    'EmployeeListView',
    'EmployeePreviewView',
    'EmployeeReservationCreateView',
    'EmployeeReservationDeleteView',
    'EmployeeReservationListView',
    'EmployeeReservationUpdateView',
    'EmployeeUpdateView',
    'IndexView',
    'LoginView',
    'LogoutView',
]
